SELECT MONTH(START_DATE) AS MONTH
     , CAR_ID
     , COUNT(*)          AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE CAR_ID IN (  
                  SELECT  CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE START_DATE BETWEEN '20220801' AND '20221031'
                   GROUP BY CAR_ID    
                   HAVING COUNT(*) >= 5		
				 )
   AND START_DATE BETWEEN '20220801' AND '20221031'                 
 GROUP BY 
       MONTH(START_DATE)
     , CAR_ID    
 ORDER BY 
       MONTH
     , CAR_ID DESC;