SELECT A.CATEGORY
     , SUM(B.SALES) AS TOTAL_SALES
  FROM BOOK A
       INNER JOIN BOOK_SALES B ON B.BOOK_ID = A.BOOK_ID
 WHERE B.SALES_DATE LIKE '2022-01%'
 GROUP BY A.CATEGORY
 ORDER BY A.CATEGORY;