SELECT A.YEAR
	 , A.MONTH
	 , A.GENDER
	 , COUNT(DISTINCT USER_ID) AS USERS
  FROM (SELECT DATE_FORMAT(B.SALES_DATE, '%Y') AS YEAR
             , DATE_FORMAT(B.SALES_DATE, '%m') AS MONTH
        	 , A.GENDER
			 , A.USER_ID
          FROM USER_INFO A
               INNER JOIN ONLINE_SALE B ON B.USER_ID = A.USER_ID
         WHERE GENDER IS NOT NULL
       ) A
 GROUP BY 
       A.YEAR
	 , A.MONTH
	 , A.GENDER
 ORDER BY 
       A.YEAR
	 , A.MONTH
	 , A.GENDER