SELECT CATEGORY
     , MAX_PRICE
	 , PRODUCT_NAME
  FROM (SELECT CATEGORY
             , MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
        	 , RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRICE_RANK 
			 , PRODUCT_NAME
          FROM FOOD_PRODUCT
         WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
		) A
 WHERE PRICE_RANK = 1
 ORDER BY
       MAX_PRICE DESC