WITH DC_RATE AS
(
SELECT CAR_TYPE
     , DISCOUNT_RATE
  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE DURATION_TYPE = '30일 이상'
)

SELECT A.CAR_ID
     , A.CAR_TYPE
	 , FLOOR(A.FEE) AS FEE
  FROM (
        SELECT A.CAR_ID
             , A.CAR_TYPE
        	 , A.DAILY_FEE * ((100 - B.DISCOUNT_RATE) / 100) * 30 AS FEE
          FROM CAR_RENTAL_COMPANY_CAR A
			   INNER JOIN DC_RATE B ON B.CAR_TYPE = A.CAR_TYPE
         WHERE A.CAR_TYPE IN ('세단','SUV')
		   AND A.CAR_ID NOT IN (SELECT CAR_ID
		                          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
								 WHERE START_DATE <= '2022-11-30'
								   AND END_DATE >= '2022-11-01')
		) A
 WHERE A.FEE BETWEEN 500000 AND 1999999
 ORDER BY
       A.FEE DESC
	 , A.CAR_TYPE 
	 , A.CAR_ID DESC;